// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

namespace aspnetserver.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220119152317_FirstInit")]
    partial class FirstInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "this a post 1 and i realy Love it",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "this a post 2 and i realy Love it",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "this a post 3 and i realy Love it",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "this a post 4 and i realy Love it",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "this a post 5 and i realy Love it",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "this a post 6 and i realy Love it",
                            Title = "Post 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
